source "https://rubygems.org"

gem 'rake'

# MySQL, PostgreSQL
gem 'activerecord', '~> 3.2.19'
gem 'activerecord-mysql2-adapter'
gem 'iconv'
gem 'pg'

# MongoDB
gem 'mongo'
gem 'bson_ext'

# Redis
gem 'redis'

# Riak
gem 'riak-client'
